name: Main

on: [push]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Load super-linter env variables
        run: |
          cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Lint code base
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -r requirements.txt

      - name: Run test with pytest
        run:
          pytest tests
